### ISSUE TITLE
400 status code in creating

### ISSUE THREAD

**Issue by janpaulalmanoche** [MacsiDigital/laravel-zoom#17]
$user = $zoom->user->create([
        'name' => 'Test Name',
        'first_name' => 'First Name',
        'last_name' => 'Last Name',
        'email' => 'test@test.com',
        'password' => 'secret',
        'type' => 1
    ]);
    $meeting = $user->meetings()->create([
    	'type' => '2',
    	'start_time' => '2019-06-29T20:00:00Z'
    ]);
    $registrant = $meeting->registrants()->create([
    	'email' => 'registratn@domain.com',
    	'first_name' => 'Test',
    	'last_name' => 'Registrant'
    ]);

**Comment by amitmeghare** [comment]
User will create if you buy any package like Pro or higher, but still facing issue while creating registrants, getting 400 status code.

**Comment by colinhall17** [comment]
Hi

Apologies in the delay in coming back to you, when I created this package it was a quick build for a project I needed it for and I made it open source in case it would help someone. 

With the increased use of Zoom around the world its gaining some traction, so I've built 3 new versions for Laravel 5.5 upwards, make sure you select the correct version for your version of Laravel.

The issue was probably the date field, but we now use Laravel date casting, so pass in a Carbon instance and the API should handle the correct save format

Open a new issue with any problems.
