### ISSUE TITLE
User Create returns 400 error status code

### ISSUE THREAD

**Issue by ai-tushar** [MacsiDigital/laravel-zoom#26]
Hello,
thank you so much for creating a organised api for zoom. zoom's default api is very unorganised i think.
however, while trying to create a new user, i am getting 400 error status.
i tried the same code given in example.

    $zoom = new \MacsiDigital\Zoom\Zoom;
        $user = $zoom->user->create([
            'name' => 'Ashraful Islam',
            'first_name' => 'Ashraful',
            'last_name' => 'Islam',
            'email' => 'ashraf@ict-euro.com',
            'password' => '123123',
            'type' => 1
        ]);

and exception throws `400 status code`

so i checked zoom accounts jwp app logs. and in the log i can see the response details.
the response is below,

    {
        endpoint: "https://api.zoom.us/v2/users",
        response_headers: [
            "Set-Cookie: zm_aid=""; Domain=.zoom.us; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly"
        ],
        date_time: "2020-04-09 17:25:06",
        method: "POST",
        request_body: "{"action":"create","user_info":["first_name","last_name","email","type","password"]}",
        response: {
            code: 300,
            message: "Request Body should be a valid JSON object."
        },
        request_headers: [
            "accept: application/json",
            "authorization: ******",
            "connection: close",
            "content-type: application/json",
            "user-agent: GuzzleHttp/6.5.1 curl/7.59.0 PHP/7.2.8"
        ],
        request_params: [
        ],
        http_status: "400"
    } 

they say the request body is not valid json string. another main concern i see is, the request body does not contain any of my data !! it only contains the parameter names. and not the value.
so is there any problem in the data preparation method ? or we should pass the data in defferent format ?

**Comment by bemendozaa** [comment]
Al dia de hoy, me he topado con el mismo error, pudo solucionarlo?, se ve interesante la implementación

**Comment by colinhall17** [comment]
Hi

Apologies in the delay in coming back to you, when I created this package it was a quick build for a project I needed it for and I made it open source in case it would help someone. 

With the increased use of Zoom around the world its gaining some traction, so I've built 3 new versions for Laravel 5.5 upwards, make sure you select the correct version for your version of Laravel.

I think the issue is the user wasn't being wrapped in its own containing array.  This is now taken care of in the new version

Open a new issue with any problems.
