### ISSUE TITLE
meeting update error

### ISSUE THREAD

**Issue by bit503sv** [MacsiDigital/laravel-zoom#39]
I have the follow errors when I try to update a meeting
![image](https://user-images.githubusercontent.com/66502210/85079389-ecce5a00-b183-11ea-9061-a62676f36da5.png)

![image](https://user-images.githubusercontent.com/66502210/85079512-3cad2100-b184-11ea-89c5-678dabe27de5.png)

the last image is when I try to change the end_times or the end_date_time for my meeting

Thank you for your help!

**Comment by colinhall17** [comment]
Hi,

What version of laravel-zoom and Laravel are you using?  

Can you also post an example of the data you are trying to update, it sounds like its missing a required field or the data cast is not correct

**Comment by bit503sv** [comment]
I use the version 2.0.3 of this library and 5.8 of Laravel.

and this error appears only when is a meeting with recurrence.

**Comment by colinhall17** [comment]
Hi

The first issue is now resolved, we will pass back an empty instance of the resource if there is not one present.

The second issue is also resolved, the issue was we were only passing dirty attributes on the update call.   We now pass all attributes for the recurrence model as some fields are required on update.  

Just one thing to note when updating, you will need to pass in a start date when updating by 'end_times', otherwise Zoom will use the last occurrence date as the start date.
