### ISSUE TITLE
Meeting Settings within createAttribute

### ISSUE THREAD

**Issue by craiglockhart81** [MacsiDigital/laravel-zoom#7]
The meeting settings are being replaced with blank values.

$data = [
   "topic" =>"Test",
   "type"=> 2,
   "start_time" => "2019-07-28T13:00:00Z",
   "duration"=>60,
   "settings"=> [
      "host_video"=> true,
      "participant_video"=> true,
      "join_before_host"=>true,
      "approval_type"=> int(0)
];

array:7 [▼
  "topic" => "Test"
  "type" => 2
  "start_time" => "2019-07-28T13:00:00Z"
  "duration" => 60
  "recurrence" => []
  "tracking_fields" => []
  "settings" => []
]

**Comment by colinhall17** [comment]
There are helper functions and objects for sub elements, so you would do as follows

$settings = $zoom->meeting_setting->make(["host_video"=> true, "participant_video"=> true, "join_before_host"=>true, "approval_type"=> 0]);
    
$meeting = $zoom->meeting->setUserID($user->getID())->make(['type' => '2', 'start_time' => '2019-07-29T20:00:00Z'])->addSettings($settings)->save();

Also from v1.0.11 we will now be returning the object on save rather than the Guzzle response array.  There is now a helper function to get the response object getResponse()
