### ISSUE TITLE
I have multiple user and can create individual meeting 

### ISSUE THREAD

**Issue by ojha007** [MacsiDigital/laravel-zoom#78]
i have multiple user and can create independent  meeting and user who created the metting can approve the metting  .how can i manage this scenario  .

**Comment by colinhall17** [comment]
Hi @ojha007 

I believe to be able to that you need to use Master and Sub Accounts, but this package is not designed to use the Master and Sub Accounts so you would need to implement that part independent of this package.

Otherwise each user would need there own API Key and Secret, we recently made changes so that on the entry Model you can add individual API Keys and Secrets to connect, the info is in the [docs](https://github.com/MacsiDigital/laravel-zoom#custom-settings )
