### ISSUE TITLE
Unable to create user

### ISSUE THREAD

**Issue by souvik07manu** [MacsiDigital/laravel-zoom#87]
I can't implement Zoom at Laravel even after I'm a pro member of Zoom. I upgrade my account to Business Plan.
I used this package in my laravel application “GitHub - MacsiDigital/laravel-zoom: Laravel Zoom Package”…
After creating a zoom jwt app, I got the App id and app key from there.
I can’t create a user in Zoom.
I’m getting this error when I’m going to create a user.

**(MacsiDigital\API\Exceptions\HttpException

HTTP Request returned Status Code 400. No privilege.)**

My code is:
$user = Zoom::user()->create([

        'first_name' => 'First Name',

        'last_name' => 'Last Name',

        'email' => 'test@test.com',

        'password' => 'secretkkkk'

    ]);

I did not find any solution . please help me how to use zoom in laravel app.

**Comment by colinhall17** [comment]
Hi @souvik07manu 

Thanks for getting in touch

This is not an issue with the Zoom API package but an issue with your privileges on your account.  The API is just a communication mechanism to send data to Zoom and retrieve the response from Zoom for the API call.  In this case you have received the response with a response code - so the API is working fine.

I've just had a quick look at the Zoom API documentation and this is what they state.

Error Code: 200
No privilege.
No permission, please contact Zoom customer support.

You mentioned in your post that you are a Pro user and have the Business Plan - the Pro and Business plans are 2 different plans - the Business plan is required for user creation - but it would be best to speak to Zoom about this, I know they have a strange setup for user creation and its not a feature we have ever had to implement.

I will leave the issue open incase someone else in the community can give more insight into implementing with user creation.

**Comment by souvik07manu** [comment]
Thanks @colinhall17 
                                **My account is pro. Can I create a user with this zoom account.Please help me**

**Comment by colinhall17** [comment]
@souvik07manu 

No it needs to be a Business account

**Comment by souvik07manu** [comment]
Thanks @colinhall17 
Can I **create users and meetings in zoom** if I upgrade to a **business plan**?
I contacted Zoom but did not return any positive feedback. Please help @colinhall17 .
I have looked forward to your reply @colinhall17 .

**Comment by colinhall17** [comment]
Looking at the pricing table the only account you can create users or sub-accounts on is the business plan, but it would be best to confirm with Zoom.

**Comment by colinhall17** [comment]
Hi @souvik07manu 

I've had a chance to have a look, first of all apologies, I was thinking of sub accounts not users with the business account.  A user you can create with a pro plan.  

I just did a quick google search and the 'No Privledge' appears to be a common issue, there are numerous posts on the Zoom Dev Forum.

The main reasons for receiving this appear to be because you are on a free account, on a trial or there is no billing method setup.

I just ran the following code

`$user = Zoom::user()->create([
  'first_name' => 'Test',
  'last_name' => 'User',
  'email' => 'test@macsi.co.uk',
  'password' => '*********'
]);`

And it created a user in my account even though I'm not on a Pro plan.  But my billing details are still in my account from when I did have a Pro plan.

Also it does state that the user account setting up the new user has to have the correct scopes `user:write:admin user:write`

Hope this helps
